remote_theme: artemsheludko/flexible-jekyll
host: 0.0.0.0
title: Minhajul Anwar's Blog
description: > # this means to ignore newlines until "baseurl:"
  I write on coding, labguages, frameworks, tools, news, reviews, documentation, tutorials, projects and misc activity etc.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: intent/follow?screen_name=MinhajulAnwar #if your site has a twitter account, enter it here

# Author Settings
author: Minhajul Anwar # add your name
author-img: minhajul-anwar.jpg # add your photo
about-author: Software Engineer. # add description
social-twitter: intent/follow?screen_name=MinhajulAnwar # add your Twitter handle
social-facebook: minhajul.anwar.me # add your Facebook handle
social-github: minhajme # add your Github handle
social-linkedin: minhajulanwar/# add your Linkedin handle
social-email: contact@resgef.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: G-2F2C14LVYS # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
